name: Aplicar Funções no PostgreSQL

on:
  push:
    branches:
      - main
    paths:
      - "sql/functions/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Autenticar no Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Criar ou Atualizar Funções
        run: |
          for file in sql/functions/*.sql; do
            echo "Executando $file"
            PGPASSWORD=${{ secrets.AZURE_POSTGRES_PASSWORD }} psql \
              -h ${{ secrets.AZURE_POSTGRES_SERVER }}.postgres.database.azure.com \
              -U ${{ secrets.AZURE_POSTGRES_USER }}@${{ secrets.AZURE_POSTGRES_SERVER }} \
              -d postgres \
              -f $file
          done
